import { test, expect } from './electron-fixture.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';

// Operator criteria for the newly approved prototype source; never implements UI.
const address='demo@fresh.protoflow.test',secret='FreshDemo42!';
const hasConversation=!!process.env.PROTOFLOW_MANIFEST_ID&&await fs.access(path.join(process.cwd(),'.protoflow/versions',process.env.PROTOFLOW_MANIFEST_ID,'files/prototype/conversation.html')).then(()=>true,()=>false);
async function details(page,email=address,password=secret){await page.locator('#email').fill(email);await page.locator('#password').fill(password);}
async function enter(page,email=address,password=secret){await details(page,email,password);await page.locator('#submit').click();}
async function conversation(page){await page.goto(`${process.env.PROTOFLOW_APPLICATION_URL.replace(/#.*$/,'')}#conversation`,{waitUntil:'networkidle'});}

test('actual Electron window mounts an independent React root at the required viewport',async({page})=>{
  expect(await page.evaluate(()=>({width:innerWidth,height:innerHeight,react:Object.keys(document.getElementById('root')).some(key=>key.startsWith('__reactContainer'))}))).toEqual({width:1000,height:760,react:true});
  expect(page.url()).not.toContain('/prototype/');expect(await page.locator('iframe').count()).toBe(0);
});
test('login initial state and fictional details are visible',async({page})=>{await expect(page.getByRole('heading',{name:"Let's get started"})).toBeVisible();await expect(page.locator('#status')).toHaveText('Ready for a fresh start');await expect(page.locator('#email')).toBeEmpty();await expect(page.locator('#password')).toBeEmpty();});
test('empty login identifies both required fields and focuses email',async({page})=>{await page.locator('#submit').click();await expect(page.locator('#email-error')).toHaveText('Email is required.');await expect(page.locator('#password-error')).toHaveText('Password is required.');await expect(page.locator('#email')).toBeFocused();});
test('malformed address and short password fail validation',async({page})=>{await enter(page,'bad','123');await expect(page.locator('#email-error')).toHaveText('Use a valid email address.');await expect(page.locator('#password-error')).toHaveText('Use 8 or more characters.');});
test('wrong fictional credentials cannot enter',async({page})=>{await enter(page,address,'WrongDemo42!');await expect(page.locator('#login-error')).toHaveText("Those demo details don't match.");await expect(page.locator('#status')).toHaveText('Try the fictional test details');});
test('valid fictional login shows the workspace',async({page})=>{await enter(page);await expect(page.getByRole('heading',{name:'Demo workspace'})).toBeVisible();await expect(page.locator('#user-email')).toHaveText(address);await expect(page.locator('#status')).toHaveText('Workspace opened');});
test('email normalization matches the prototype',async({page})=>{await enter(page,'  DEMO@FRESH.PROTOFLOW.TEST  ');await expect(page.locator('#user-email')).toHaveText(address);});
test('keyboard submit opens one workspace',async({page})=>{await details(page);await page.locator('#password').press('Enter');await expect(page.getByRole('heading',{name:'Demo workspace'})).toBeVisible();await expect(page.locator('#user-email')).toHaveCount(1);});
test('leaving clears credentials and resets the login state',async({page})=>{await enter(page);await page.locator('#logout').click();await expect(page.locator('#email')).toBeEmpty();await expect(page.locator('#password')).toBeEmpty();await expect(page.locator('#status')).toHaveText('You can start again');await expect(page.locator('#email')).toBeFocused();});
test('reload resets the in-memory demonstration',async({page})=>{await enter(page);await page.reload();await expect(page.locator('#status')).toHaveText('Ready for a fresh start');await expect(page.locator('#password')).toBeEmpty();});
test('fictional login does not call an authentication service',async({page})=>{const requests=[];page.on('request',request=>{if(/^https?:/.test(request.url()))requests.push(request.url());});await enter(page);await expect(page.locator('#status')).toHaveText('Workspace opened');expect(requests).toEqual([]);});

test.describe('new conversation source version',()=>{
  test.skip(!hasConversation,'Conversation is not present in this frozen Git checkpoint');
  test('initial conversation has one fixed welcome',async({page})=>{await conversation(page);await expect(page.getByRole('heading',{name:'A fresh conversation'})).toBeVisible();await expect(page.locator('#messages article')).toHaveCount(1);await expect(page.locator('#messages')).toContainText('Welcome! What would you like to explore?');});
  test('whitespace is rejected without appending messages',async({page})=>{await conversation(page);await page.locator('#message').fill('   ');await page.locator('#send').click();await expect(page.locator('#message-error')).toHaveText('Write a message to continue.');await expect(page.locator('#messages article')).toHaveCount(1);});
  test('send appends trimmed user message and fixed reply once',async({page})=>{await conversation(page);await page.locator('#message').fill('  A clean idea  ');await page.locator('#send').click();await expect(page.locator('#messages article.user p')).toHaveText('A clean idea');await expect(page.locator('#messages article.assistant').last()).toContainText('A fresh idea! This is the fixed demonstration reply.');await expect(page.locator('#message')).toBeEmpty();await expect(page.locator('#status')).toHaveText('Your idea has a reply');});
  test('double submit does not duplicate a cleared message',async({page})=>{await conversation(page);await page.locator('#message').fill('One idea');await page.locator('#message-form').evaluate(form=>{form.requestSubmit();form.requestSubmit();});await expect(page.locator('#messages article.user')).toHaveCount(1);await expect(page.locator('#messages article')).toHaveCount(3);});
  test('message markup is literal text and cannot create HTML',async({page})=>{await conversation(page);const value='<img src=x onerror="window.compromised=true">';await page.locator('#message').fill(value);await page.locator('#send').click();await expect(page.locator('#messages article.user p')).toHaveText(value);await expect(page.locator('#messages img')).toHaveCount(0);expect(await page.evaluate(()=>window.compromised)).toBeUndefined();});
  test('fresh conversation clears messages and reload remains fresh',async({page})=>{await conversation(page);await page.locator('#message').fill('Discard me');await page.locator('#send').click();await page.locator('#clear').click();await expect(page.locator('#messages article')).toHaveCount(1);await expect(page.locator('#status')).toHaveText('A fresh conversation is ready');await page.reload();await expect(page.locator('#messages article')).toHaveCount(1);await expect(page.locator('#status')).toHaveText('Waiting for your first idea');});
  test('fixed replies do not call an external AI service',async({page})=>{await conversation(page);const requests=[];page.on('request',request=>{if(/^https?:/.test(request.url()))requests.push(request.url());});await page.locator('#message').fill('Local only');await page.locator('#send').click();await expect(page.locator('#status')).toHaveText('Your idea has a reply');expect(requests).toEqual([]);});
});
